package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author jp
 */
public class Main_menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_menu
     */
    public Main_menu() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddBookBttn = new javax.swing.JButton();
        ViewRecordsbBttn = new javax.swing.JButton();
        AddStudentBttn = new javax.swing.JButton();
        SearchBttn = new javax.swing.JButton();
        IssueBookBttn = new javax.swing.JButton();
        adduserbttn = new javax.swing.JButton();
        ReturnBookBttn = new javax.swing.JButton();
        LogoutBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIBRARY MANAGEMENT SYSTEM");

        AddBookBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddBookBttn.setText("Add Book");
        AddBookBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookBttnActionPerformed(evt);
            }
        });

        ViewRecordsbBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewRecordsbBttn.setText("View Records");
        ViewRecordsbBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecordsbBttnActionPerformed(evt);
            }
        });

        AddStudentBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddStudentBttn.setText("Add Student");
        AddStudentBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentBttnActionPerformed(evt);
            }
        });

        SearchBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchBttn.setText("Search");
        SearchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBttnActionPerformed(evt);
            }
        });

        IssueBookBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IssueBookBttn.setText("Issue Book");
        IssueBookBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookBttnActionPerformed(evt);
            }
        });

        adduserbttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adduserbttn.setText("Add User");
        adduserbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserbttnActionPerformed(evt);
            }
        });

        ReturnBookBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReturnBookBttn.setText("Return Book");
        ReturnBookBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookBttnActionPerformed(evt);
            }
        });

        LogoutBttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LogoutBttn.setText("Logout");
        LogoutBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ViewRecordsbBttn)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adduserbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LogoutBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddBookBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddStudentBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IssueBookBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ReturnBookBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBookBttn)
                    .addComponent(AddStudentBttn)
                    .addComponent(IssueBookBttn)
                    .addComponent(ReturnBookBttn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewRecordsbBttn)
                    .addComponent(SearchBttn)
                    .addComponent(adduserbttn)
                    .addComponent(LogoutBttn))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewRecordsbBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecordsbBttnActionPerformed
        new view_records().setVisible(true);
        
    }//GEN-LAST:event_ViewRecordsbBttnActionPerformed

    private void AddBookBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookBttnActionPerformed
        new add_book().setVisible(true);
    }//GEN-LAST:event_AddBookBttnActionPerformed

    private void AddStudentBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentBttnActionPerformed
        new add_student().setVisible(true);
    }//GEN-LAST:event_AddStudentBttnActionPerformed

    private void IssueBookBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookBttnActionPerformed
        new issue_book().setVisible(true);
    }//GEN-LAST:event_IssueBookBttnActionPerformed

    private void ReturnBookBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookBttnActionPerformed
        new return_book().setVisible(true);
    }//GEN-LAST:event_ReturnBookBttnActionPerformed

    private void SearchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBttnActionPerformed
        new search().setVisible(true);
    }//GEN-LAST:event_SearchBttnActionPerformed

    private void adduserbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserbttnActionPerformed
        new Add_user().setVisible(true);
    }//GEN-LAST:event_adduserbttnActionPerformed

    private void LogoutBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBttnActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_LogoutBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookBttn;
    private javax.swing.JButton AddStudentBttn;
    private javax.swing.JButton IssueBookBttn;
    private javax.swing.JButton LogoutBttn;
    private javax.swing.JButton ReturnBookBttn;
    private javax.swing.JButton SearchBttn;
    private javax.swing.JButton ViewRecordsbBttn;
    private javax.swing.JButton adduserbttn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
